# Generated by Django 4.1.7 on 2023-03-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpay', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
