# Generated by Django 4.1.7 on 2023-03-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpay', '0003_alter_user_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
